server:
  port: 9002

spring:
  application:
    name: cloud-payment-service-nacos
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.53.166:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'