server:
  port: 8086

spring:
  application:
    name: cloud-payment-service
  cloud:
    consul:
      host: 192.168.53.166
      port: 8500
      discovery:
        service-name: ${spring.application.name}