server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: cloud-payment-service
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/learn?useUnicode=true&characterEncoding=utf-8&useSSL=false
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.learn.springcloud.entities

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    # 客户端向服务端发送心跳的间隔时间，单位为秒（默认是30秒）
    lease-renewal-interval-in-seconds: 1
    # Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时提出服务
    lease-expiration-duration-in-seconds: 2
    # 配置Eureka实例名称显示和显示IP等信息
#    instance-id: payment8001
#    prefer-ip-address: true
