server:
  port: 83

spring:
  application:
    name: cloud-order-service-nacos
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.53.166:8848

# 消费者简要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://cloud-payment-service-nacos